version: 2.1
jobs:
  api_build:
    docker:
      - image: cimg/node:26.5.0

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: Package.lock cleanup
          command: |
            cd membrane-api
            rm -rf node_modules
            rm -f package-lock.json
            npm install --legacy-peer-deps
      

  api_deploy:
    docker:
    - image: cimg/node:26.5.0
      auth: 
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Docker image build-deploy
          command: |
            cd membrane-api
            docker build -t $DOCKERHUB_USERNAME/membrane_api:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
            docker push $DOCKERHUB_USERNAME/membrane_api:latest




workflows:
  membrane_deploy: 
    jobs:
      - api_build
      - api_deploy: 
          context: DOCKERHUB_AUTH
          filters: pipeline.git.branch == "membrane-preview" # run the api_deploy workflow when action is triggered on the preview branch