version: 2.1
jobs:
  api_deployment_process:
    docker:
      - image: cimg/node:26.5.0
        auth: 
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: Package.lock cleanup
          command: |
            rm -rf node_modules
            rm -f package-lock.json
            npm install --legacy-peer-deps
      
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/membrane_api:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD docker.io
            docker push $DOCKERHUB_USERNAME/membrane_api:latest



workflows:
  membrane_deploy: 
    jobs:
      - api_deployment_process:
          context: DOCKERHUB_AUTH